repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
      - id: pytest
        name: pytest
        entry: sh
        language: python
        types: [python]
        args: ["./test.sh"]
